### ISSUE TITLE
Decide upon project names

### ISSUE THREAD

**Issue by tl8roy** [tl8roy/patina#1]
**Patina** was suggested in the comments as a good name that isn't already in use. As I like it too, the initial project name will be Patina.

**Comment by tl8roy** [comment]
Also suggested **Knurling**

**Comment by tl8roy** [comment]
Suggestion from the talk: **Oxdize**

**Comment by lambda** [comment]
I suggested Patina, and I wholeheartedly support that name. But for some further discussion:

### Pros

* Means oxidized coating on metal
  * Commonly used for copper. Think "Rust on Copper"
  * On copper, is considered attractive and is protective
  * Embedded systems tend to make heavy use of copper
* Suggests color palette to use for branding: coppery color, and blue-green color
* Is fairly simple to pronounce, even for non-native English speakers
  * Syllables are CV structure, which is the most common syllable structure in languages
  * Consonants are among the most common consonants across languages worldwide
  * At least one variant of each of the vowels are among the most common vowels used across languages (though see in cons below)
* "Oxidize" is already used by the Oxidize embedded Rust conference series
  * Also, "Oxide Computer Company" is a new hardware startup which has an interest in Rust
  * If we re-use this name for a beginner/hobbyist-friendly set of tooling, instructions, and hardware, it might cause confusion about whether that's the focus of the Oxidize conferences or if they are also oriented toward professionals
* "Knurling" has a few disadvantages
  * Slightly more obscure than Patina, I would say
  * Silent first letter, spelling and figuring out how to pronounce might be harder for non-native speakers
  * CVC syllables are less common than CV, consonant clusters like the "rl" cluster in the middle can be tricky, and the individual "r" and "l" consonants are some of the trickiest in English for non-native speakers. Heck, even as a native English speaker, I have trouble pronouncing the English "r"
* patina.dev ~is~ was available; I just registered it, but haven't hosted anything there yet

### Cons

* Is another term you have to learn and learn what it means relative to Rust and embedded systems
  * In some cases, less clever and more obvious names can be good, like CircuitPython which is a bit more obvious from the name what it's related to
* Even though patina on copper can be desirable sometimes, it generally isn't in actual circuits, that's one reason why you gold plate exposed contacts not covered by the solder mask
  * However, this embrace of a term that can be seen as negative fits nicely in with Rust, whether you believe it refers to the patina on iron or the fungus on crops
* Pronunciation can differ between native English speakers of different dialects, and differ from the simplest phonetic reading that an international audience might expect:
  * US: /pəˈtiː.nə/ (this is how I pronounce it)
  * UK: /ˈpæ.tɪ.nə/ (and some dialects in the US according to Wiktionary)
  * Common in other languages/simplest phonetic reading: /ˈpa.ti.na/
* May sound a bit fancy, rather than simple or fun

**Comment by tl8roy** [comment]
Since there has been no further comment, and Knurling-rs has been announced, I am closing this off and sticking with Patina.
